### ISSUE TITLE
Speicher- und Ladefunktion für Probandentest notwendig

### ISSUE THREAD

**Issue by Rina14** [Rina14/Abschlussarbeit#16]
Diese Grundfunktionen vereinfachen ja den ganzen Prozess und man kann später weiterspielen bzw. -testen. Wann meinst Du, wäre das ungefähr realisierbar? 
Wann die Probandentests genau anstehen, kann ich noch nicht sagen, vielleicht in einer Woche oder zwei.

**Comment by JirkaDellOro** [comment]
Ich habe die Sound-Klasse auf das FUDGE-Soundsystem umgebaut. Jetzt loopt es auch ordentlich. Ich denke, der Issue kann damit geschlossen werden.
