### ISSUE TITLE
move Transition

### ISSUE THREAD

**Issue by Rina14** [Rina14/Abschlussarbeit#18]
Um Bilder z.B. von A nach B zu bewegen könnte man eine move Transition bzw. eine ganze MoveTransition() (Transition-Klasse) definieren, um abwechslungsreichere Bewegungen einbauen zu können. Dabei unterscheidet man zwischen 
- move
- moveoutright, moveoutleft, moveouttop, moveoutbottom
- moveinright, moveinleft, moveintop, moveinbottom

Bei der move Transition wird das Bild zur gewünschten Position (xpos, ypos) innerhalb von 0,5s (Standard) hinbewegt. Bei den anderen wird das Bild dabei von der jeweiligen Seite aus ins Bild ein- oder aus dem Bild ausgeblendet. Ist nun auch alles in der Analyseforderung drin. Wäre auch für das Spielerlebnis ziemlich schön, das drin zu haben.

**Comment by JirkaDellOro** [comment]
Bezieht sich auf Charaktere
