### ISSUE TITLE
Vor- und Zurück-Buttons innerhalb einer Novel-Page

### ISSUE THREAD

**Issue by Rina14** [Rina14/Abschlussarbeit#22]
ich möchte versuchen einen Vertrag mit Hilfe der Novel-Pages darzustellen. Das heißt, man soll die Pages "umblättern" können und dafür ist eine Vor- und Zurück-Funktion mit diesen zwei Buttons notwendig.

**Comment by JirkaDellOro** [comment]
Da Du dir einige Buttons wünschst, scheint mir nun der geschickteste Ansatz zu sein, dir Buttons zu liefern, die Du dann selbst mit der erforderlichen Funktion versorgst. Der Vertrag und das Blättern ist schließlich leicht abbildbar, es fehlt lediglich die Interaktionsmöglichkeit

**Comment by Rina14** [comment]
Genau, ja.

**Comment by JirkaDellOro** [comment]
So, bin durch. Beliebige Menüs mit Buttons sind vorbereitet. Am Ende habe ich gemerkt, dass ich die für deinen Blätterwunsch gar nicht brauchte, aber für später.

**Comment by JirkaDellOro** [comment]
Ich habe dir prototypischen Code zum Blättern damit gebaut, siehe Zeile 29 bis 42 in Scene0:
```typescript
      let pages: string[] = ["Seite 1", "Seite 2", "Seite 3"];
      let current: number = 0;
      let flip = { back: "Back", next: "Next", done: "Close these pages" };
      let choice: string;
      ƒT.Novel.addClass("flip");
      do {
        ƒT.Novel.print(pages[current]);
        choice = await ƒT.Menu.getInput(flip, "flip");
        switch (choice) {
          case flip.back: current = Math.max(0, current - 1); break;
          case flip.next: current = Math.min(2, current + 1); break;
        }
      } while (choice != flip.done);
      ƒT.Novel.close();
```

**Comment by JirkaDellOro** [comment]
Und ein prototypisches permanentes Menu habe ich auch mal gebastelt, siehe Zeile 69 bis 80
```typescript
    let menuHelloOptions = {
      riem: "Hallo Riem",
      jirka: "Hallo Jirka",
      close: "Aus"
    };

    let menuHello = ƒT.Menu.create(menuHelloOptions, sayHello, "helloMenu");
    function sayHello(_option: string): void {
      console.log(_option);
      if (_option == menuHelloOptions.close)
        menuHello.close();
    }
```

Das einzige, was hier jetzt neu ist und für dich ungewohnt, ist die Callback-Funktion. Du schreibst also eine Funktion, hier `sayHello`  die eine gewählte Option entgegen nimmt. Die Optionen hast Du wie üblich definiert, hier `menuHelloOptions`. In der Funktion reagierst Du einfach darauf, hier wird der Optionstext ausgegeben oder das Menü geschlossen, wenn die Option `close` gewählt wurde. 

Statt `getInput` nutzt Du nun die `create`-Methode der Menü-Klasse und übergibst als zweiten Parameter deine Callback-Funktion.

Das war's

**Comment by Rina14** [comment]
Super, vielen Dank :D 

Habe aber noch eine kurze Frage: Wenn man das Menü wegklickt, ist es komplett weg. Was müsste ich tun, damit man einstellen kann, dass das wieder angezeigt wird?

**Comment by JirkaDellOro** [comment]
Soll es immer angezeigt werden oder willst Du es wieder verwenden, es soll also mal da sein mal nicht?

**Comment by JirkaDellOro** [comment]
Für den ersten Fall schließt Du es einfach nie.

Für den zweiten Fall gibt es mehrere Ansätze:
- kannst Du es einfach neu konstruieren (charmant, weil ich dann jetzt nichts machen müsste)
- ich baue dir eine open-Methode, mit der Du es wieder öffnen kannst, wenn Du es geschlossen hattest
- ich baue eine show/hide-Methode die es un-/sichtbar macht

**Comment by Rina14** [comment]
Hmm, die Idee hinter dem Out-Of-Game-Menu war ja eigentlich bspw. Reiter wie Preferences für z.B. Sound-Regler einzubauen etc. ein Einstellungsmenü also. Aber nein, lass das erstmal so. Vielleicht verwende ich das für etwas anderes, da würde ich keine show/hide-Methode brauchen, aber mal schauen

**Comment by Rina14** [comment]
Wobei, ich habe das doch richtig im Kopf. Das würde doch gehen? Wenn eine show/hide-Methode existiert, kann ich daraus ja ein Einstellungsmenü machen, oder?

**Comment by Rina14** [comment]
Dafür ist eigentlich das andere Issue aufgemacht worden, aber das ist jetzt auch nicht so dringend, ich würde den anderen Issue aber evtl wiedereröffnen. Das was ich hier gebraucht habe ist ja geklärt.

**Comment by JirkaDellOro** [comment]
Nicht-Modale Menüs haben nun eine open-Methode, damit kann man sie wieder öffnen, wenn sie geschlossen wurden.

Modale Menüs schließen nicht mehr automatisch, wenn ESC gedrückt wird
