### ISSUE TITLE
Commit 20.11.2020

### ISSUE THREAD

**Issue by JirkaDellOro** [Rina14/Abschlussarbeit#6]
Habe meine letzten Commits gepusht. Folgendes musst Du berücksichtigen, was Du in meinem TheaterTest implementiert findest

1. Locations: wie besprochen im neuen Schema  (Zeile 20-29)
1. ich habe für dich beispielhaft mal einen Zustandsspeicher angelegt, der Name ist beliebig. Ich habe in `progress` genannt. Damit kannst Du also Zustände, Scores, Entscheidungen der Rezipienten protokollieren und später auswerten. (Zeile 50-53, 61 und in Scene0 Zeile 50)
1. die Zentralisierung der Szenenfolge klappt auch, Damit habe das Stück umgebaut so dass nicht mehr von Scene0 auf Scene1 verwiesen wird, sondern Scene0 endet und Scene1 aufgerufen wird, sofern `progress.goneRight` zutrifft. Der Verweis innerhalb von Scenen funktioniert aber immer noch. Wichtig ist, dass auch beim Szenenaufruf mit `act` das `await` genutzt wird.
1. `await` soll in der Regel für alles genutzt werden, was Zeit braucht und nicht instantan geschieht. Auch die Bilder müssen geladen werden, daher soll nun auch vor `showLocation` und `showCharacter` ein `await` stehen. Ein überflüssiges `await` schadet nicht, VSCode weist aber darauf hin, dass es überflüssig ist.
1. die Transition-Logik habe ich implementiert und auch eine erste Transition, ein Überblenden der Bilder. Siehe Scene1 Zeile 11. Im `Stage.update` wird die gewünschte Transition und die Dauer in Millisekunden angegeben. Ein weiterer Parameter für Tuning ist vorgesehen und kommt ggf. bei komplexeren Transitionen zum Einsatz.
1. ich habe Typ-Deklarationen für Character und Location eingeführt, so werden Schreibfehler bei der Definition erkannt und der Autor schon von VSCode darauf hingewiesen.

Ich hoffe Du kommst damit klar. Melde dich wenn es klemmt.

**Comment by JirkaDellOro** [comment]
Hast Du die Änderungen schon bei dir eingepflegt? Ich habe heute noch einige recht gravierende gemacht und würde die gerne committen und pushen. Oder soll' ich in einen anderen Branch pushen? Oder ist es dir wurscht, weil deine Arbeit derzeit noch nicht so weit ist, dass es sich lohnt hier etwas einzupflegen?

**Comment by Rina14** [comment]
sorry, sehe das jetzt erst. Habe keine Benachrichtigung bekommen, dass du das hier eröffnet hast.

**Comment by Rina14** [comment]
Also da ich es erst jetzt gesehen und gelesen habe, habe ich noch nichts eingepflegt und Du kannst ruhig pushen. Ich ziehe es mir dann lokal und schaue dann, wie ich zurechtkomme. Meine Arbeit steht beim Implementieren eher noch am Anfang (hatte nur versuchsweise den Anfang mal gemacht gehabt, den ich getrost wieder löschen kann und mit den Änderungen erneut einfügen kann), also wurde noch nicht viel implementiert, da Änderungen im Drehbuch vorgesehen sind sowie Grafiken erstellt werden müssen.

**Comment by JirkaDellOro** [comment]
Ok, dann ist das einfach. Das Schema ist jetzt auch simpler und konsistenter, die Neuimplementation leichter. Ich habe meinen Progress gestern noch in einen eigenen Branch gepusht und merge den jetzt. Ich schreibe in einem anderen Issue zu den Änderungen.

**Comment by JirkaDellOro** [comment]
PS: mein TheaterTest enthält auch weiter das voll lauffähige Beispiel, das werde ich auch in Zukunft so halten. Da kannst Du immer spicken.

**Comment by Rina14** [comment]
Perfekt, danke.
